---
title: "Allostatic scoring _AP code"
output: html_document
---

```{r setup, include=FALSE}
#Output = ("~/Documents/BBSP/Dr. Jaspers lab/Research Projects/2021 -2022  Allostatic load Research/3. Data/3. R studio Analysis/Final analysis /revised data")
cur_date = "062122"

library(readxl)
library(tidyverse)
library(reshape2)
library(dplyr)
library(magrittr)

# reading in file
allostatic_loading_df = data.frame(read_excel("~/Documents/BBSP/Dr. Jaspers lab/Research Projects/2021 -2022  Allostatic load Research/3. Data/3. R studio Analysis/Final analysis /revised data/Allostatic_Mediator_Data_062422ab.xlsx", sheet = 2)) 
```

```{r}
# viewing the dataset initially helps ensure it was read it properly and gives a view of what it looks like
print(allostatic_loading_df)
```

```{r}
# creating all dfs to be analyzed
nonsmoker_df = allostatic_loading_df %>%
    # using a pipe (%>%) to filter the group column in the df for non-smokers only
    filter(Group == "NS")
smoker_df = allostatic_loading_df %>%
    filter(Group == "CS")

# splitting the df based on group and race, so to make the code more efficient
split_allostatic_df = allostatic_loading_df %>%
    # grouping by group then race
    group_by(Group, Race, Sex) %>%
    # splitting the df based on those variables
    group_split()

#Smokers 
black_female_smoker_df = split_allostatic_df[[1]] 
black_male_smoker_df = split_allostatic_df[[2]] 
white_female_smoker_df = split_allostatic_df[[3]]
white_male_smoker_df = split_allostatic_df[[4]]

#Nonsmokers 
black_female_nonsmoker_df = split_allostatic_df[[5]] 
black_male_nonsmoker_df = split_allostatic_df[[6]]
white_female_nonsmoker_df = split_allostatic_df[[7]]
white_male_nonsmoker_df = split_allostatic_df[[8]]

# viewing the the data frames
print(nonsmoker_df)
print(smoker_df)
#print(split_allostatic_df) #prints all of the data frames possible (all of the ones shown below)

print(black_female_smoker_df)
print(black_male_smoker_df)
print(white_female_smoker_df)
print(white_male_smoker_df)

print(black_female_nonsmoker_df)
print(black_male_nonsmoker_df)
print(white_female_nonsmoker_df)
print(white_male_nonsmoker_df)

```

```{r} 

## there is an issue somewhere here - 
mediator_score = function(df){
    # always use these next lines to describe the inputs, outputs, and purpose of your function
    
    # """
    # Creating a scoring function for each mediator.
    # :param (input): initial df (df)
    # :output: df containing the variable (biomarker) name, subject ID, and score
    # """
    
    # creating an empty df to store values
    score_df = data.frame()
    
    # getting all variable names for loop to iterate through
    mediators = unique(df$Variable)  #makes sure the mediators do not repeat
    
    # your iterator (in this case 'i') can be any letter or word, but typically in computer science i or j are used
    for (i in 1:length(mediators)){

        # filtering df for each mediator
        filtered_df = df %>%
            filter(Variable == mediators)
        
        # now iterating through each value of the filtered_df, since we want to access each value
        for (j in 1:length(filtered_df$Value)){
        print(filtered_df$Value[j])
            # score = (mediator value - mediator min)/ (mediator max - mediator min)
            mediator_score_formula = (filtered_df$Value[j] - min(filtered_df$Value))/(max(filtered_df$Value) - min(filtered_df$Value))
            
            # storing mediator, subject id, and score
            values_vector = cbind(mediators[i], df$Subject_ID[j], mediator_score_formula)
        
            score_df = rbind(score_df, values_vector)
        }
    }
 
    # renaming columns
    colnames(score_df) = c("Variable", "Subject_ID", "Mediator_Score")
    
    # for some reason the Mediator_Score is a character type, so changing to a numeric
    score_df$Mediator_Score = as.numeric(as.character(score_df$Mediator_Score))
    score_df$Variable = as.character(score_df$Variable)
    score_df$Subject_ID = as.character(score_df$Subject_ID)
    return(score_df)
}

#testing to see if the function "mediator_score" works 

mediator_score(nonsmoker_df)
```

```{r}
# applying the function to the data using function(data), in this case the function is named "mediator_score" | the data are the different dataframes created in lines 24-65 | on the left we are defining the name of the new dataframe that will contain the score output 

NS_mediator_score_df = mediator_score(nonsmoker_df)
CS_mediator_score_df = mediator_score(smoker_df)
black_NS_mediator_score_df = mediator_score(black_nonsmoker_df)
black_CS_mediator_score_df = mediator_score(black_smoker_df)
white_NS_mediator_score_df = mediator_score(white_nonsmoker_df)
white_CS_mediator_score_df = mediator_score(white_smoker_df)


black_female_CS_mediator_score_df = mediator_score(black_female_smoker_df)
print(black_male_smoker_df)
print(white_female_smoker_df)
print(white_male_smoker_df)

print(black_female_nonsmoker_df)
print(black_male_nonsmoker_df)
print(white_female_nonsmoker_df)
print(white_male_nonsmoker_df)


# viewing results of one of the dataframes
NS_mediator_score_df
```

```{r}
allostatic_score = function(mediator_score_df){
    # """
    # Creating a scoring function for allostatic load.
    # :param (input): mediator score df (mediator_score_df)
    # :output: df containing the variable (biomarker) name, subject ID, and score
    # """
    
    # creating a vector for variables that increase atherosclerotic risk
    allostatic_load_biomarkers = c('Cortisol','Noradrenaline','Hba1c','Fibrinogen','CRP')
    
    # filtering df for these allostatic load biomarkers
    load_df = mediator_score_df %>%
        filter(Variable %in% allostatic_load_biomarkers)
    
    # filtering for HDL
    HDL_df = mediator_score_df %>%
        filter(Variable == "HDL")

    # allostatic score = sum of scores of all load biomarkers - sum HDL score
    allostatic_score = sum(load_df$Mediator_Score) - sum(HDL_df$Mediator_Score)
    
    return(allostatic_score)
}
```

```{r}
# calling allostatic_score function
NS_allostatic_score_df = allostatic_score(NS_mediator_score_df)
CS_allostatic_score_df = allostatic_score(CS_mediator_score_df)
black_NS_allostatic_score_df = allostatic_score(black_NS_mediator_score_df)
black_CS_allostatic_score_df = allostatic_score(black_CS_mediator_score_df)
white_NS_allostatic_score_df = allostatic_score(white_NS_mediator_score_df)
white_CS_allostatic_score_df = allostatic_score(white_CS_mediator_score_df)
```

